### ISSUE TITLE
Mac OS 64 bit version contains 32 bit binaries

### ISSUE THREAD

**Issue by otheus** [amankhoza/synergy-binaries#1]
Greetings. Thanks for making these available. Unfortunately, the version provided for MacOS (the latest stable one, https://github.com/amankhoza/synergy-binaries/blob/master/synergy-v1.8.8-stable-MacOSX-x86_64.dmg ) contains i386 binaries, which does not execute on Catalina and probably even older Macs. 

```
% ./synergyc
zsh: bad CPU type in executable: ./synergyc
% file *
Synergy:  Mach-O 64-bit executable x86_64
synergyc: Mach-O executable i386
synergys: Mach-O executable i386
syntool:  Mach-O executable i386
c10267@ydWLI-U1-36-253 MacOS % pwd
/Applications/Synergy.app/Contents/MacOS
% uname -a
Darwin ydWLI-U1-36-253.uibk.ac.at 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
```

Oddly, the output of `arch` is `i386`. See https://support.apple.com/en-us/HT208436

**Comment by amankhoza** [comment]
Unfortunately, Apple dropped support for 32-bit apps starting with Catalina, so if there are any i386 binaries in the synergy binary it won't work. Have you tried v1.9.0-rc3?

**Comment by leric** [comment]
I have just installed 1.9.0-rc3 binary on macOS 10.15, it works.

**Comment by amankhoza** [comment]
Nice thanks for testing @leric closing this issue since 1.9.0-rc3 works on Catalina.
