### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by terragady** [amankhoza/synergy-binaries#2]
Hi, is it possible that you compile the newest stable version?

**Comment by amankhoza** [comment]
For me the latest freely available versions in this repo work fine, so I have no need to compile newer versions myself, however if you do want to try this you can find instructions for compiling synergy-core here:

https://github.com/symless/synergy-core/wiki/Compiling

**Comment by boxav** [comment]
@amankhoza i followed instruction on https://github.com/symless/synergy-core/wiki/Compiling#linux and got 5 files in bin folder but i dont know how to make it a installer similar .deb?
